runtime: java
vm: true

resources:
  cpu: 16
  memory_gb: 60
  disk_size_gb: 100

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always
